### ISSUE TITLE
error encounter in example2

### ISSUE THREAD

**Issue by wangjqspace** [mungpeter/RAMAplot#1]
Dear Sir,

I have tried to use the script to run example 2 and encounter an error.
In the folder 2_md_heatmap, I run the script 
$ 2_rama_m_heatmap.csh 2 11 fgf21-wt-s2.fasta 200 fgf21-wt png templ_metrics.wt.traj 1 1 . /amber20/bin/cpptraj

The error message is:
AttributeError: 'Namespace' object has no attribute 'smooth'

Below is the output from the run. Could you suggest what could be the problem? I am using ubuntu 20.04. Thank you.

JQ

####output information#####
CPPTRAJ: Trajectory Analysis. V5.1.0
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_

| Date/time: 04/05/22 21:30:22
| Available memory: 196.979 GB

INPUT: Reading input from 'tmp.fgf21-wt.traj'
  [parm ./fgf21-wt-s2.prot.prmtop]
	Reading './fgf21-wt-s2.prot.prmtop' as Amber Topology
	Radius Set: modified Bondi radii (mbondi)
  [trajin ./fgf21-wt-s2.prod_gamd.nc 1 500 1]
	Reading './fgf21-wt-s2.prod_gamd.nc' as Amber NetCDF
Warning: Trajectory box type is 'Truncated octahedron' but topology box type is 'None'.
Warning: Setting topology box information from trajectory.
  [dihedral 2_phi :1@C :2@N :2@CA :2@C out fgf21-wt.S200.phi.out]
    DIHEDRAL: [:1@C]-[:2@N]-[:2@CA]-[:2@C]
              Output range is -180 to 180 degrees.
  [dihedral 2_psi :2@N :2@CA :2@C :3@N out fgf21-wt.S200.psi.out]
    DIHEDRAL: [:2@N]-[:2@CA]-[:2@C]-[:3@N]
              Output range is -180 to 180 degrees.
  [dihedral 3_phi :2@C :3@N :3@CA :3@C out fgf21-wt.Q201.phi.out]
    DIHEDRAL: [:2@C]-[:3@N]-[:3@CA]-[:3@C]
              Output range is -180 to 180 degrees.
  [dihedral 3_psi :3@N :3@CA :3@C :4@N out fgf21-wt.Q201.psi.out]
    DIHEDRAL: [:3@N]-[:3@CA]-[:3@C]-[:4@N]
              Output range is -180 to 180 degrees.
  [dihedral 4_phi :3@C :4@N :4@CA :4@C out fgf21-wt.G202.phi.out]
    DIHEDRAL: [:3@C]-[:4@N]-[:4@CA]-[:4@C]
              Output range is -180 to 180 degrees.
  [dihedral 4_psi :4@N :4@CA :4@C :5@N out fgf21-wt.G202.psi.out]
    DIHEDRAL: [:4@N]-[:4@CA]-[:4@C]-[:5@N]
              Output range is -180 to 180 degrees.
  [dihedral 5_phi :4@C :5@N :5@CA :5@C out fgf21-wt.R203.phi.out]
    DIHEDRAL: [:4@C]-[:5@N]-[:5@CA]-[:5@C]
              Output range is -180 to 180 degrees.
  [dihedral 5_psi :5@N :5@CA :5@C :6@N out fgf21-wt.R203.psi.out]
    DIHEDRAL: [:5@N]-[:5@CA]-[:5@C]-[:6@N]
              Output range is -180 to 180 degrees.
  [dihedral 6_phi :5@C :6@N :6@CA :6@C out fgf21-wt.S204.phi.out]
    DIHEDRAL: [:5@C]-[:6@N]-[:6@CA]-[:6@C]
              Output range is -180 to 180 degrees.
  [dihedral 6_psi :6@N :6@CA :6@C :7@N out fgf21-wt.S204.psi.out]
    DIHEDRAL: [:6@N]-[:6@CA]-[:6@C]-[:7@N]
              Output range is -180 to 180 degrees.
  [dihedral 7_phi :6@C :7@N :7@CA :7@C out fgf21-wt.P205.phi.out]
    DIHEDRAL: [:6@C]-[:7@N]-[:7@CA]-[:7@C]
              Output range is -180 to 180 degrees.
  [dihedral 7_psi :7@N :7@CA :7@C :8@N out fgf21-wt.P205.psi.out]
    DIHEDRAL: [:7@N]-[:7@CA]-[:7@C]-[:8@N]
              Output range is -180 to 180 degrees.
  [dihedral 8_phi :7@C :8@N :8@CA :8@C out fgf21-wt.S206.phi.out]
    DIHEDRAL: [:7@C]-[:8@N]-[:8@CA]-[:8@C]
              Output range is -180 to 180 degrees.
  [dihedral 8_psi :8@N :8@CA :8@C :9@N out fgf21-wt.S206.psi.out]
    DIHEDRAL: [:8@N]-[:8@CA]-[:8@C]-[:9@N]
              Output range is -180 to 180 degrees.
  [dihedral 9_phi :8@C :9@N :9@CA :9@C out fgf21-wt.Y207.phi.out]
    DIHEDRAL: [:8@C]-[:9@N]-[:9@CA]-[:9@C]
              Output range is -180 to 180 degrees.
  [dihedral 9_psi :9@N :9@CA :9@C :10@N out fgf21-wt.Y207.psi.out]
    DIHEDRAL: [:9@N]-[:9@CA]-[:9@C]-[:10@N]
              Output range is -180 to 180 degrees.
  [dihedral 10_phi :9@C :10@N :10@CA :10@C out fgf21-wt.A208.phi.out]
    DIHEDRAL: [:9@C]-[:10@N]-[:10@CA]-[:10@C]
              Output range is -180 to 180 degrees.
  [dihedral 10_psi :10@N :10@CA :10@C :11@N out fgf21-wt.A208.psi.out]
    DIHEDRAL: [:10@N]-[:10@CA]-[:10@C]-[:11@N]
              Output range is -180 to 180 degrees.
  [dihedral 11_phi :10@C :11@N :11@CA :11@C out fgf21-wt.S209.phi.out]
    DIHEDRAL: [:10@C]-[:11@N]-[:11@CA]-[:11@C]
              Output range is -180 to 180 degrees.
  [dihedral 11_psi :11@N :11@CA :11@C :12@N out fgf21-wt.S209.psi.out]
    DIHEDRAL: [:11@N]-[:11@CA]-[:11@C]-[:12@N]
              Output range is -180 to 180 degrees.
---------- RUN BEGIN -------------------------------------------------

PARAMETER FILES (1 total):
 0: fgf21-wt-s2.prot.prmtop, 144 atoms, 11 res, box: Truncated octahedron, 1 mol

INPUT TRAJECTORIES (1 total):
 0: 'fgf21-wt-s2.prod_gamd.nc' is a NetCDF AMBER trajectory with coordinates, time, box, Parm fgf21-wt-s2.prot.prmtop (Truncated octahedron box) (reading 500 of 500)
  Coordinate processing will occur on 500 frames.

BEGIN TRAJECTORY PROCESSING:
.....................................................
ACTION SETUP FOR PARM 'fgf21-wt-s2.prot.prmtop' (20 actions):
  0: [dihedral 2_phi :1@C :2@N :2@CA :2@C out fgf21-wt.S200.phi.out]
	 [:1@C](1) [:2@N](1) [:2@CA](1) [:2@C](1)
  1: [dihedral 2_psi :2@N :2@CA :2@C :3@N out fgf21-wt.S200.psi.out]
	 [:2@N](1) [:2@CA](1) [:2@C](1) [:3@N](1)
  2: [dihedral 3_phi :2@C :3@N :3@CA :3@C out fgf21-wt.Q201.phi.out]
	 [:2@C](1) [:3@N](1) [:3@CA](1) [:3@C](1)
  3: [dihedral 3_psi :3@N :3@CA :3@C :4@N out fgf21-wt.Q201.psi.out]
	 [:3@N](1) [:3@CA](1) [:3@C](1) [:4@N](1)
  4: [dihedral 4_phi :3@C :4@N :4@CA :4@C out fgf21-wt.G202.phi.out]
	 [:3@C](1) [:4@N](1) [:4@CA](1) [:4@C](1)
  5: [dihedral 4_psi :4@N :4@CA :4@C :5@N out fgf21-wt.G202.psi.out]
	 [:4@N](1) [:4@CA](1) [:4@C](1) [:5@N](1)
  6: [dihedral 5_phi :4@C :5@N :5@CA :5@C out fgf21-wt.R203.phi.out]
	 [:4@C](1) [:5@N](1) [:5@CA](1) [:5@C](1)
  7: [dihedral 5_psi :5@N :5@CA :5@C :6@N out fgf21-wt.R203.psi.out]
	 [:5@N](1) [:5@CA](1) [:5@C](1) [:6@N](1)
  8: [dihedral 6_phi :5@C :6@N :6@CA :6@C out fgf21-wt.S204.phi.out]
	 [:5@C](1) [:6@N](1) [:6@CA](1) [:6@C](1)
  9: [dihedral 6_psi :6@N :6@CA :6@C :7@N out fgf21-wt.S204.psi.out]
	 [:6@N](1) [:6@CA](1) [:6@C](1) [:7@N](1)
  10: [dihedral 7_phi :6@C :7@N :7@CA :7@C out fgf21-wt.P205.phi.out]
	 [:6@C](1) [:7@N](1) [:7@CA](1) [:7@C](1)
  11: [dihedral 7_psi :7@N :7@CA :7@C :8@N out fgf21-wt.P205.psi.out]
	 [:7@N](1) [:7@CA](1) [:7@C](1) [:8@N](1)
  12: [dihedral 8_phi :7@C :8@N :8@CA :8@C out fgf21-wt.S206.phi.out]
	 [:7@C](1) [:8@N](1) [:8@CA](1) [:8@C](1)
  13: [dihedral 8_psi :8@N :8@CA :8@C :9@N out fgf21-wt.S206.psi.out]
	 [:8@N](1) [:8@CA](1) [:8@C](1) [:9@N](1)
  14: [dihedral 9_phi :8@C :9@N :9@CA :9@C out fgf21-wt.Y207.phi.out]
	 [:8@C](1) [:9@N](1) [:9@CA](1) [:9@C](1)
  15: [dihedral 9_psi :9@N :9@CA :9@C :10@N out fgf21-wt.Y207.psi.out]
	 [:9@N](1) [:9@CA](1) [:9@C](1) [:10@N](1)
  16: [dihedral 10_phi :9@C :10@N :10@CA :10@C out fgf21-wt.A208.phi.out]
	 [:9@C](1) [:10@N](1) [:10@CA](1) [:10@C](1)
  17: [dihedral 10_psi :10@N :10@CA :10@C :11@N out fgf21-wt.A208.psi.out]
	 [:10@N](1) [:10@CA](1) [:10@C](1) [:11@N](1)
  18: [dihedral 11_phi :10@C :11@N :11@CA :11@C out fgf21-wt.S209.phi.out]
	 [:10@C](1) [:11@N](1) [:11@CA](1) [:11@C](1)
  19: [dihedral 11_psi :11@N :11@CA :11@C :12@N out fgf21-wt.S209.psi.out]
Warning: Select residues: res 1 out of range (12 > 11)
	 [:11@N](1) [:11@CA](1) [:11@C](1) [:12@N](0)
Warning: One or more masks have no atoms.
Warning: Setup incomplete for [dihedral]: Skipping
----- fgf21-wt-s2.prod_gamd.nc (1-500, 1) -----
 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Complete.

Read 500 frames and processed 500 frames.
TIME: Avg. throughput= 51498.6095 frames / second.

ACTION OUTPUT:
TIME: Analyses took 0.0000 seconds.

DATASETS (20 total):
	2_phi "2_phi" (double, torsion), size is 500 (4.000 kB)
	2_psi "2_psi" (double, torsion), size is 500 (4.000 kB)
	3_phi "3_phi" (double, torsion), size is 500 (4.000 kB)
	3_psi "3_psi" (double, torsion), size is 500 (4.000 kB)
	4_phi "4_phi" (double, torsion), size is 500 (4.000 kB)
	4_psi "4_psi" (double, torsion), size is 500 (4.000 kB)
	5_phi "5_phi" (double, torsion), size is 500 (4.000 kB)
	5_psi "5_psi" (double, torsion), size is 500 (4.000 kB)
	6_phi "6_phi" (double, torsion), size is 500 (4.000 kB)
	6_psi "6_psi" (double, torsion), size is 500 (4.000 kB)
	7_phi "7_phi" (double, torsion), size is 500 (4.000 kB)
	7_psi "7_psi" (double, torsion), size is 500 (4.000 kB)
	8_phi "8_phi" (double, torsion), size is 500 (4.000 kB)
	8_psi "8_psi" (double, torsion), size is 500 (4.000 kB)
	9_phi "9_phi" (double, torsion), size is 500 (4.000 kB)
	9_psi "9_psi" (double, torsion), size is 500 (4.000 kB)
	10_phi "10_phi" (double, torsion), size is 500 (4.000 kB)
	10_psi "10_psi" (double, torsion), size is 500 (4.000 kB)
	11_phi "11_phi" (double, torsion), size is 500 (4.000 kB)
	11_psi "11_psi" (double, torsion), size is 0
    Total data set memory usage is at least 76.000 kB

DATAFILES (20 total):
  fgf21-wt.S200.phi.out (Standard Data File):  2_phi
  fgf21-wt.S200.psi.out (Standard Data File):  2_psi
  fgf21-wt.Q201.phi.out (Standard Data File):  3_phi
  fgf21-wt.Q201.psi.out (Standard Data File):  3_psi
  fgf21-wt.G202.phi.out (Standard Data File):  4_phi
  fgf21-wt.G202.psi.out (Standard Data File):  4_psi
  fgf21-wt.R203.phi.out (Standard Data File):  5_phi
  fgf21-wt.R203.psi.out (Standard Data File):  5_psi
  fgf21-wt.S204.phi.out (Standard Data File):  6_phi
  fgf21-wt.S204.psi.out (Standard Data File):  6_psi
  fgf21-wt.P205.phi.out (Standard Data File):  7_phi
  fgf21-wt.P205.psi.out (Standard Data File):  7_psi
  fgf21-wt.S206.phi.out (Standard Data File):  8_phi
  fgf21-wt.S206.psi.out (Standard Data File):  8_psi
  fgf21-wt.Y207.phi.out (Standard Data File):  9_phi
  fgf21-wt.Y207.psi.out (Standard Data File):  9_psi
  fgf21-wt.A208.phi.out (Standard Data File):  10_phi
  fgf21-wt.A208.psi.out (Standard Data File):  10_psi
  fgf21-wt.S209.phi.out (Standard Data File):  11_phi
  fgf21-wt.S209.psi.out (Standard Data File):  11_psi
Warning: Set '11_psi' contains no data.
Warning: File 'fgf21-wt.S209.psi.out' has no sets containing data.

RUN TIMING:
TIME:		Init               : 0.0001 s (  0.19%)
TIME:		Trajectory Process : 0.0097 s ( 26.96%)
TIME:		Action Post        : 0.0000 s (  0.00%)
TIME:		Analysis           : 0.0000 s (  0.00%)
TIME:		Data File Write    : 0.0262 s ( 72.67%)
TIME:		Other              : 0.0001 s (  0.00%)
TIME:	Run Total 0.0360 s
---------- RUN END ---------------------------------------------------
TIME: Total execution time: 0.0407 seconds.
--------------------------------------------------------------------------------
To cite CPPTRAJ use:
Daniel R. Roe and Thomas E. Cheatham, III, "PTRAJ and CPPTRAJ: Software for
  Processing and Analysis of Molecular Dynamics Trajectory Data". J. Chem.
  Theory Comput., 2013, 9 (7), pp 3084-3095.

 ## Generate combined phi-psi files: fgf21-wt.S200
fgf21-wt.S200.rama.out

 ## Generate Ramachandran plot: fgf21-wt.S200
[1] 106165
 ## Generate combined phi-psi files: fgf21-wt.Q201
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.S200.rama.out.bz2 -img fgf21-wt.S200.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.Q201.rama.out

 ## Generate Ramachandran plot: fgf21-wt.Q201
[1] 106359
 ## Generate combined phi-psi files: fgf21-wt.G202
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.Q201.rama.out.bz2 -img fgf21-wt.Q201.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.G202.rama.out

 ## Generate Ramachandran plot: fgf21-wt.G202
[1] 106555
 ## Generate combined phi-psi files: fgf21-wt.R203
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.G202.rama.out.bz2 -img fgf21-wt.G202.rama_histo.png -ref ../.././pyrama_data/pref_glycine.data.bz2 -res Gly -t_step 1 -c_step 1
fgf21-wt.R203.rama.out

 ## Generate Ramachandran plot: fgf21-wt.R203
[1] 106749
 ## Generate combined phi-psi files: fgf21-wt.S204
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.R203.rama.out.bz2 -img fgf21-wt.R203.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.S204.rama.out

 ## Generate Ramachandran plot: fgf21-wt.S204
  * Pre-proline: S204
[1] 106945
 ## Generate combined phi-psi files: fgf21-wt.P205
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.S204.rama.out.bz2 -img fgf21-wt.S204.rama_histo.png -ref ../.././pyrama_data/pref_preproline.data.bz2 -res PreP -t_step 1 -c_step 1
fgf21-wt.P205.rama.out

 ## Generate Ramachandran plot: fgf21-wt.P205
[1] 107139
 ## Generate combined phi-psi files: fgf21-wt.S206
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.P205.rama.out.bz2 -img fgf21-wt.P205.rama_histo.png -ref ../.././pyrama_data/pref_proline.data.bz2 -res Pro -t_step 1 -c_step 1
fgf21-wt.S206.rama.out

 ## Generate Ramachandran plot: fgf21-wt.S206
[1] 107333
 ## Generate combined phi-psi files: fgf21-wt.Y207
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.S206.rama.out.bz2 -img fgf21-wt.S206.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.Y207.rama.out

 ## Generate Ramachandran plot: fgf21-wt.Y207
[1] 107527
 ## Generate combined phi-psi files: fgf21-wt.A208
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.Y207.rama.out.bz2 -img fgf21-wt.Y207.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.A208.rama.out

 ## Generate Ramachandran plot: fgf21-wt.A208
[1] 107721
 ## Generate combined phi-psi files: fgf21-wt.S209
Traceback (most recent call last):
  File "../.././combine_column.py", line 51, in <module>
    main( )
  File "../.././combine_column.py", line 21, in main
    f2_df = pd.read_csv(args.file_2, delimiter=delim)
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/jiaqi/.local/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'fgf21-wt.S209.psi.out'
Traceback (most recent call last):
  File "../.././2x_rama_md_heatmap_gen.py", line 270, in <module>
    main()
  File "../.././2x_rama_md_heatmap_gen.py", line 70, in main
    smooth = float(args.smooth)
AttributeError: 'Namespace' object has no attribute 'smooth'
[1]    Exit 1                        ../.././2x_rama_md_heatmap_gen.py -in fgf21-wt.A208.rama.out.bz2 -img fgf21-wt.A208.rama_histo.png -ref ../.././pyrama_data/pref_general.data.bz2 -res Gen
fgf21-wt.S209.rama.out
rm: cannot remove 'fgf21-wt.S209.psi.out': No such file or directory

 ## Generate Ramachandran plot: fgf21-wt.S209
fasta: Subscript out of range.

**Comment by mungpeter** [comment]
bug fixed. Apparently a typo in a common function I never tested, and yet is correct in other related codes...
